name: arrivo_web_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  fpdart: ^0.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  uuid: ^3.0.7
  enum_to_string: ^2.0.1
  flutter_web_data_table: ^1.0.0
  string_extensions: ^0.1.4
  intl: ^0.17.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  kt_dart: ^1.0.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.1
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  lint: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true